0 and search strategy
fulei345/tapaal-gui pull request #5
Opened 2022-04-15 12:22 UTC by fulei345

2022-04-19 11:11 UTC, faje18 approved these changes

2022-04-19 13:02 UTC, rherum18 approved these changes

2022-04-19 13:07 UTC, MikkelTJensen requested changes

2022-04-19 13:07 UTC, MikkelTJensen commented on src/dk/aau/cs/verification/QueryResult.java
>  			buffer.append("Property is ");
```suggestion
```

2022-04-19 13:12 UTC, MikkelTJensen commented on src/dk/aau/cs/verification/QueryResult.java
> +			}
```suggestion
			buffer.append(satisfied ? "satisfied." : "not satisfied.");
			if(percent > 0.0){
				buffer.append(" " + percent + "% of the runs satisfied the property");
			}
```

2022-04-20 12:30 UTC, rherum18 approved these changes

2022-04-20 12:31 UTC, MikkelTJensen approved these changes

2022-04-20 12:31 UTC, merged